### ISSUE TITLE
项目copy下来后本地安装报错

### ISSUE THREAD

**Issue by tokiii** [NeglectedByBoss/TcStatInterface#1]
![krnd qzo_ mizf5l5 xb 49](https://cloud.githubusercontent.com/assets/3972083/23937630/77f2269e-0993-11e7-8236-0b51a9cb9d98.png)

**Comment by Tamicer** [comment]
@tokiii 确认后呢

**Comment by tokiii** [comment]
` <receiver android:name=".core.TcUploadCoreReceiver"
          android:process="statCore">`

这句代码：android:process="statCore"去掉就可以了

**Comment by Tamicer** [comment]
@tokiii 这是防止被杀死 声明了进程而以

**Comment by tokiii** [comment]
安装不上去，如果加上这句的话

**Comment by sxyseo** [comment]
> `<receiver android:name=".core.TcUploadCoreReceiver" android:process="statCore">`
> 
> 这句代码：android:process="statCore"去掉就可以了

去掉会重新生成。
