### ISSUE TITLE
6.0 之后在application中初始化失败

### ISSUE THREAD

**Issue by Doraemonhub** [NeglectedByBoss/TcStatInterface#4]
6.0之后在application中进行初始化，getDeviceinfo中需要READ_PHONE_STATE，请问如何设置？

**Comment by Tamicer** [comment]
@Doraemonhub 应该是权限的问题

**Comment by Tamicer** [comment]
@Doraemonhub 运行时权限需要适配

**Comment by Doraemonhub** [comment]
因为init在application中，这个时候还无法进行权限处理

**Comment by Tamicer** [comment]
@Doraemonhub 拿着源码改吧
