### ISSUE TITLE
页面结束时如果想传入参数，需要怎么添加呢？

### ISSUE THREAD

**Issue by Doraemonhub** [NeglectedByBoss/TcStatInterface#5]
在页面结束时recordpageend之前需要记录一个参数，需要怎么传入呢，我尝试了一下使用onpageparamer,这个不行，他会把之前的数据重置了，有没有合适的方法呢？

**Comment by Tamicer** [comment]
@Doraemonhub 还有这操作？

**Comment by Doraemonhub** [comment]
有啊，自己又加了个paramer用于pageend时添加参数，已解决

**Comment by Tamicer** [comment]
拿着源码你自己随便改吧
