### ISSUE TITLE
设置完上报策略后，在实际的上报前，没有看到不同上报策略的处理逻辑。

### ISSUE THREAD

**Issue by 2022happynew** [NeglectedByBoss/TcStatInterface#8]
设置完上报策略后，在实际的上报前，没有看到不同上报策略的处理逻辑。求指导！！

**Comment by Tamicer** [comment]
@zhushi91 贴代码

**Comment by zhushi91** [comment]
`//切后台时数据上传
TcStatSdk.getInstance(aContext).send();`

**Comment by zhushi91** [comment]
`    private synchronized void onForegroundChanged(Context aContext, boolean aIsForeground) {
        // 更新前后台状态
        isForeground = aIsForeground;
        //前后台变换时访问report
        reportData(aContext);
        //记录前后台切换
        if (aIsForeground) {
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground true");
            }
            // app唤醒
            DataConstruct.storeAppAction("3");
            //切前台时开始计时
            scheduleStart();

        } else {
            //切后台
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground false");
            }
            //切后台时数据上传
            TcStatSdk.getInstance(aContext).send();
            // 切后台停止计时
            scheduleStop();

        }
    }`

**Comment by zhushi91** [comment]
`private synchronized void onForegroundChanged(Context aContext, boolean aIsForeground) {
        // 更新前后台状态
        isForeground = aIsForeground;
        //前后台变换时访问report
        reportData(aContext);
        //记录前后台切换
        if (aIsForeground) {
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground true");
            }
            // app唤醒
            DataConstruct.storeAppAction("3");
            //切前台时开始计时
            scheduleStart();

        } else {
            //切后台
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground false");
            }
            //切后台时数据上传
            TcStatSdk.getInstance(aContext).send();
            // 切后台停止计时
            scheduleStop();

        }
    }`

**Comment by zhushi91** [comment]
`        // 更新前后台状态
        isForeground = aIsForeground;
        //前后台变换时访问report
        reportData(aContext);
        //记录前后台切换
        if (aIsForeground) {
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground true");
            }
            // app唤醒
            DataConstruct.storeAppAction("3");
            //切前台时开始计时
            scheduleStart();

        } else {
            //切后台
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground false");
            }
            //切后台时数据上传
            TcStatSdk.getInstance(aContext).send();
            // 切后台停止计时
            scheduleStop();

        }`

**Comment by zhushi91** [comment]
`private synchronized void onForegroundChanged(Context aContext, boolean aIsForeground) {
        // 更新前后台状态
        isForeground = aIsForeground;
        //前后台变换时访问report
        reportData(aContext);
        //记录前后台切换
        if (aIsForeground) {
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground true");
            }
            // app唤醒
            DataConstruct.storeAppAction("3");
            //切前台时开始计时
            scheduleStart();
        } else {
            //切后台
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground false");
            }
            //切后台时数据上传
            TcStatSdk.getInstance(aContext).send();
            // 切后台停止计时
            scheduleStop();
        }
    }`

**Comment by 2022happynew** [comment]
private synchronized void onForegroundChanged(Context aContext, boolean aIsForeground) {
        // 更新前后台状态
        isForeground = aIsForeground;
        //前后台变换时访问report
        reportData(aContext);
        //记录前后台切换
        if (aIsForeground) {
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground true");
            }
            // app唤醒
            DataConstruct.storeAppAction("3");
            //切前台时开始计时
            scheduleStart();
        } else {
            //切后台
            if (StaticsConfig.DEBUG) {
                Log.d(LOG_TAG, "onForeground false");
            }
            //切后台时数据上传
            TcStatSdk.getInstance(aContext).send();
            // 切后台停止计时
            scheduleStop();

        }
    }

**Comment by 2022happynew** [comment]
这里直接调用reportData，而且如果aIsForeground为false。那数据不是send了两次吗？

**Comment by Tamicer** [comment]
数据上报过 再次发送就不会上报了
